const LUTADORES = [
  {
    id: "leonardo",
    nome: "Leonardo",
    forma: "Lucario",
    sprite: "img/sprites/leonardo-lucario.png",
    descricao: "Luta com precisão e espírito de equipe.",
    atributos: {
      vida: 126,
      ataque: 84,
      defesa: 72,
      velocidade: 88,
    },
    golpes: [
      {
        nome: "Pulso de Aura",
        tipo: "LUTADOR",
        poder: 58,
        precisao: 100,
        prioridade: 0,
      },
      {
        nome: "Garra de Metal",
        tipo: "AÇO",
        poder: 52,
        precisao: 95,
        prioridade: 0,
      },
      {
        nome: "Investida",
        tipo: "NORMAL",
        poder: 42,
        precisao: 100,
        prioridade: 0,
      },
      {
        nome: "Ataque Rápido",
        tipo: "NORMAL",
        poder: 36,
        precisao: 100,
        prioridade: 1,
      },
    ],
  },
  {
    id: "dalcin",
    nome: "Dalcin",
    forma: "Blacephalon",
    sprite: "img/sprites/dalcin-blacephalon.png",
    descricao: "Usa criatividade explosiva em batalha.",
    atributos: {
      vida: 112,
      ataque: 92,
      defesa: 60,
      velocidade: 98,
    },
    golpes: [
      {
        nome: "Labareda",
        tipo: "FOGO",
        poder: 62,
        precisao: 90,
        prioridade: 0,
      },
      {
        nome: "Bola Sombria",
        tipo: "FANTASMA",
        poder: 56,
        precisao: 100,
        prioridade: 0,
      },
      {
        nome: "Fagulha",
        tipo: "FOGO",
        poder: 38,
        precisao: 100,
        prioridade: 0,
      },
      {
        nome: "Ataque Rápido",
        tipo: "NORMAL",
        poder: 36,
        precisao: 100,
        prioridade: 1,
      },
    ],
  },
  {
    id: "eraldo",
    nome: "Eraldo",
    forma: "Regirock",
    sprite: "img/sprites/eraldo-regirock.png",
    descricao: "Resistência e estratégia orientam cada decisão.",
    atributos: {
      vida: 142,
      ataque: 70,
      defesa: 98,
      velocidade: 40,
    },
    golpes: [
      {
        nome: "Poder Ancestral",
        tipo: "PEDRA",
        poder: 55,
        precisao: 100,
        prioridade: 0,
      },
      {
        nome: "Cabeça de Ferro",
        tipo: "AÇO",
        poder: 57,
        precisao: 90,
        prioridade: 0,
      },
      {
        nome: "Impacto",
        tipo: "NORMAL",
        poder: 40,
        precisao: 100,
        prioridade: 0,
      },
      {
        nome: "Ataque Rápido",
        tipo: "NORMAL",
        poder: 36,
        precisao: 100,
        prioridade: 1,
      },
    ],
  },
  {
    id: "laura",
    nome: "Laura",
    forma: "Leafeon",
    sprite: "img/sprites/laura-leafeon.png",
    descricao: "Combina agilidade e conexão com a natureza.",
    atributos: {
      vida: 120,
      ataque: 80,
      defesa: 78,
      velocidade: 86,
    },
    golpes: [
      {
        nome: "Lâmina de Folha",
        tipo: "PLANTA",
        poder: 58,
        precisao: 95,
        prioridade: 0,
      },
      {
        nome: "Chicote de Vinha",
        tipo: "PLANTA",
        poder: 46,
        precisao: 100,
        prioridade: 0,
      },
      {
        nome: "Investida",
        tipo: "NORMAL",
        poder: 42,
        precisao: 100,
        prioridade: 0,
      },
      {
        nome: "Ataque Rápido",
        tipo: "NORMAL",
        poder: 36,
        precisao: 100,
        prioridade: 1,
      },
    ],
  },
  {
    id: "kurt",
    nome: "Kurt",
    forma: "Zeraora",
    sprite: "img/sprites/kurt-zeraora.png",
    descricao: "A velocidade elétrica decide os turnos.",
    atributos: {
      vida: 116,
      ataque: 90,
      defesa: 64,
      velocidade: 105,
    },
    golpes: [
      {
        nome: "Choque do Trovão",
        tipo: "ELÉTRICO",
        poder: 60,
        precisao: 95,
        prioridade: 0,
      },
      {
        nome: "Garra",
        tipo: "NORMAL",
        poder: 48,
        precisao: 100,
        prioridade: 0,
      },
      {
        nome: "Investida",
        tipo: "NORMAL",
        poder: 42,
        precisao: 100,
        prioridade: 0,
      },
      {
        nome: "Ataque Rápido",
        tipo: "NORMAL",
        poder: 36,
        precisao: 100,
        prioridade: 1,
      },
    ],
  },
  {
    id: "flores",
    nome: "Flores",
    forma: "Metagross",
    sprite: "img/sprites/flores-metagross.png",
    descricao: "Uma mente analítica conduz sua grande resistência.",
    atributos: {
      vida: 136,
      ataque: 86,
      defesa: 92,
      velocidade: 63,
    },
    golpes: [
      {
        nome: "Psíquico",
        tipo: "PSÍQUICO",
        poder: 58,
        precisao: 100,
        prioridade: 0,
      },
      {
        nome: "Garra de Metal",
        tipo: "AÇO",
        poder: 50,
        precisao: 95,
        prioridade: 0,
      },
      {
        nome: "Impacto",
        tipo: "NORMAL",
        poder: 40,
        precisao: 100,
        prioridade: 0,
      },
      {
        nome: "Ataque Rápido",
        tipo: "NORMAL",
        poder: 36,
        precisao: 100,
        prioridade: 1,
      },
    ],
  },
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = LUTADORES;
}
