"use strict";

// Nome PT-BR, nome original, tipo, categoria, poder-base, precisão e prioridade.
const DEFINICOES_GOLPES = Object.freeze({
  "aerial-ace": ["Ás dos Ares", "Aerial Ace", "VOADOR", "FÍSICO", 60, 100],
  "ancient-power": ["Poder Ancestral", "Ancient Power", "PEDRA", "ESPECIAL", 60, 100],
  "aqua-jet": ["Aqua Jato", "Aqua Jet", "ÁGUA", "FÍSICO", 40, 100, 1],
  astonish: ["Abismar", "Astonish", "FANTASMA", "FÍSICO", 30, 100],
  "aura-sphere": ["Aura Esférica", "Aura Sphere", "LUTADOR", "ESPECIAL", 80, 100],
  bite: ["Mordida", "Bite", "SOMBRIO", "FÍSICO", 60, 100],
  "bolt-strike": ["Ataque de Raios", "Bolt Strike", "ELÉTRICO", "FÍSICO", 130, 85],
  "bone-rush": ["Fúria de Ossos", "Bone Rush", "TERRESTRE", "FÍSICO", 25, 90],
  bounce: ["Ricochete", "Bounce", "VOADOR", "FÍSICO", 85, 85],
  "brave-bird": ["Pássaro Bravo", "Brave Bird", "VOADOR", "FÍSICO", 120, 100],
  "bug-bite": ["Picada", "Bug Bite", "INSETO", "FÍSICO", 60, 100],
  "bullet-punch": ["Soco Projétil", "Bullet Punch", "AÇO", "FÍSICO", 40, 100, 1],
  "bullet-seed": ["Projétil de Semente", "Bullet Seed", "PLANTA", "FÍSICO", 25, 100],
  "close-combat": ["Corpo-a-corpo", "Close Combat", "LUTADOR", "FÍSICO", 120, 100],
  crunch: ["Mastigada", "Crunch", "SOMBRIO", "FÍSICO", 80, 100],
  // Crush Grip varia com a vida do alvo; 120 é o teto usado como referência.
  "crush-grip": ["Aperto Esmagador", "Crush Grip", "NORMAL", "FÍSICO", 120, 100],
  "dark-pulse": ["Pulso Sombrio", "Dark Pulse", "SOMBRIO", "ESPECIAL", 80, 100],
  dig: ["Cavar", "Dig", "TERRESTRE", "FÍSICO", 80, 100],
  discharge: ["Descarga", "Discharge", "ELÉTRICO", "ESPECIAL", 80, 100],
  "double-kick": ["Chute Duplo", "Double Kick", "LUTADOR", "FÍSICO", 30, 100],
  "dragon-breath": ["Sopro do Dragão", "Dragon Breath", "DRAGÃO", "ESPECIAL", 60, 100],
  "dragon-claw": ["Garra de Dragão", "Dragon Claw", "DRAGÃO", "FÍSICO", 80, 100],
  "dragon-hammer": ["Martelo Dragão", "Dragon Hammer", "DRAGÃO", "FÍSICO", 90, 100],
  "dragon-pulse": ["Pulso do Dragão", "Dragon Pulse", "DRAGÃO", "ESPECIAL", 85, 100],
  "drill-run": ["Furação", "Drill Run", "TERRESTRE", "FÍSICO", 80, 95],
  "earth-power": ["Poder da Terra", "Earth Power", "TERRESTRE", "ESPECIAL", 90, 100],
  earthquake: ["Terremoto", "Earthquake", "TERRESTRE", "FÍSICO", 100, 100],
  electroweb: ["Teia Elétrica", "Electroweb", "ELÉTRICO", "ESPECIAL", 55, 95],
  ember: ["Brasa", "Ember", "FOGO", "ESPECIAL", 40, 100],
  "extreme-speed": ["Velocidade Extrema", "Extreme Speed", "NORMAL", "FÍSICO", 80, 100, 2],
  extrasensory: ["Extrassensorial", "Extrasensory", "PSÍQUICO", "ESPECIAL", 80, 100],
  "first-impression": ["Primeira Impressão", "First Impression", "INSETO", "FÍSICO", 90, 100, 2],
  "flame-charge": ["Ataque de Chamas", "Flame Charge", "FOGO", "FÍSICO", 50, 100],
  flamethrower: ["Lança-chamas", "Flamethrower", "FOGO", "ESPECIAL", 90, 100],
  "flare-blitz": ["Blitz de Labaredas", "Flare Blitz", "FOGO", "FÍSICO", 120, 100],
  "foul-play": ["Jogo Sujo", "Foul Play", "SOMBRIO", "FÍSICO", 95, 100],
  "freeze-dry": ["Liofilização", "Freeze-Dry", "GELO", "ESPECIAL", 70, 100],
  "giga-impact": ["Gigaimpacto", "Giga Impact", "NORMAL", "FÍSICO", 150, 90],
  "hammer-arm": ["Braço de Martelo", "Hammer Arm", "LUTADOR", "FÍSICO", 100, 90],
  "head-smash": ["Bate-cabeça", "Head Smash", "PEDRA", "FÍSICO", 150, 80],
  "hyper-voice": ["Hipervoz", "Hyper Voice", "NORMAL", "ESPECIAL", 90, 100],
  "ice-beam": ["Raio Congelante", "Ice Beam", "GELO", "ESPECIAL", 90, 100],
  "ice-punch": ["Soco de Gelo", "Ice Punch", "GELO", "FÍSICO", 75, 100],
  judgment: ["Julgamento", "Judgment", "NORMAL", "ESPECIAL", 100, 100],
  "knock-off": ["Derrubar", "Knock Off", "SOMBRIO", "FÍSICO", 65, 100],
  "leaf-blade": ["Lâmina de Folha", "Leaf Blade", "PLANTA", "FÍSICO", 90, 100],
  "leech-life": ["Suga-vidas", "Leech Life", "INSETO", "FÍSICO", 80, 100],
  lick: ["Lambida", "Lick", "FANTASMA", "FÍSICO", 30, 100],
  liquidation: ["Aquaríete", "Liquidation", "ÁGUA", "FÍSICO", 85, 100],
  lunge: ["Estocada", "Lunge", "INSETO", "FÍSICO", 80, 100],
  "mach-punch": ["Soco Mach", "Mach Punch", "LUTADOR", "FÍSICO", 40, 100, 1],
  megahorn: ["Megachifre", "Megahorn", "INSETO", "FÍSICO", 120, 85],
  "metal-claw": ["Garra de Metal", "Metal Claw", "AÇO", "FÍSICO", 50, 95],
  "meteor-mash": ["Meteoro Esmagador", "Meteor Mash", "AÇO", "FÍSICO", 90, 90],
  "mind-blown": ["Explosão Mental", "Mind Blown", "FOGO", "ESPECIAL", 150, 100],
  moonblast: ["Explosão Lunar", "Moonblast", "FADA", "ESPECIAL", 95, 100],
  "mud-bomb": ["Bomba de Lama", "Mud Bomb", "TERRESTRE", "ESPECIAL", 65, 85],
  "mud-shot": ["Tiro de Lama", "Mud Shot", "TERRESTRE", "ESPECIAL", 55, 95],
  "pin-missile": ["Míssil de Espinhos", "Pin Missile", "INSETO", "FÍSICO", 25, 95],
  "plasma-fists": ["Punhos de Plasma", "Plasma Fists", "ELÉTRICO", "FÍSICO", 100, 100],
  "play-rough": ["Jogo Duro", "Play Rough", "FADA", "FÍSICO", 90, 90],
  "poison-jab": ["Golpe Envenenado", "Poison Jab", "VENENOSO", "FÍSICO", 80, 100],
  "power-gem": ["Gema Poderosa", "Power Gem", "PEDRA", "ESPECIAL", 80, 100],
  psychic: ["Psíquico", "Psychic", "PSÍQUICO", "ESPECIAL", 90, 100],
  psyshock: ["Choque Psíquico", "Psyshock", "PSÍQUICO", "ESPECIAL", 80, 100],
  "pyro-ball": ["Bola Incendiária", "Pyro Ball", "FOGO", "FÍSICO", 120, 90],
  "quick-attack": ["Ataque Rápido", "Quick Attack", "NORMAL", "FÍSICO", 40, 100, 1],
  "razor-leaf": ["Folha Navalha", "Razor Leaf", "PLANTA", "FÍSICO", 55, 95],
  "relic-song": ["Canção da Relíquia", "Relic Song", "NORMAL", "ESPECIAL", 75, 100],
  scratch: ["Arranhão", "Scratch", "NORMAL", "FÍSICO", 40, 100],
  "seed-bomb": ["Bomba de Sementes", "Seed Bomb", "PLANTA", "FÍSICO", 80, 100],
  "shadow-ball": ["Bola Sombria", "Shadow Ball", "FANTASMA", "ESPECIAL", 80, 100],
  "shadow-claw": ["Garra Sombria", "Shadow Claw", "FANTASMA", "FÍSICO", 70, 100],
  "shadow-sneak": ["Furtividade nas Sombras", "Shadow Sneak", "FANTASMA", "FÍSICO", 40, 100, 1],
  slam: ["Pancada Brusca", "Slam", "NORMAL", "FÍSICO", 80, 75],
  slash: ["Talho", "Slash", "NORMAL", "FÍSICO", 70, 100],
  "sludge-bomb": ["Bomba de Lodo", "Sludge Bomb", "VENENOSO", "ESPECIAL", 90, 100],
  struggle: ["Insistência", "Struggle", "NORMAL", "FÍSICO", 50, 100],
  "solar-beam": ["Raio Solar", "Solar Beam", "PLANTA", "ESPECIAL", 120, 100],
  "sparkling-aria": ["Ária Cintilante", "Sparkling Aria", "ÁGUA", "ESPECIAL", 90, 100],
  "spirit-shackle": ["Manilha Sombria", "Spirit Shackle", "FANTASMA", "FÍSICO", 80, 100],
  stomp: ["Pisotear", "Stomp", "NORMAL", "FÍSICO", 65, 100],
  "stone-edge": ["Gume de Pedra", "Stone Edge", "PEDRA", "FÍSICO", 100, 80],
  "sucker-punch": ["Soco Enganador", "Sucker Punch", "SOMBRIO", "FÍSICO", 70, 100, 1],
  superpower: ["Superpoder", "Superpower", "LUTADOR", "FÍSICO", 120, 100],
  tackle: ["Investida", "Tackle", "NORMAL", "FÍSICO", 40, 100],
  "throat-chop": ["Golpe Enfeitiçado", "Throat Chop", "SOMBRIO", "FÍSICO", 80, 100],
  "thunder-punch": ["Soco Trovoada", "Thunder Punch", "ELÉTRICO", "FÍSICO", 75, 100],
  thunderbolt: ["Relâmpago", "Thunderbolt", "ELÉTRICO", "ESPECIAL", 90, 100],
  "u-turn": ["Fazer Retorno", "U-turn", "INSETO", "FÍSICO", 70, 100],
  "vine-whip": ["Chicote de Vinha", "Vine Whip", "PLANTA", "FÍSICO", 45, 100],
  "volt-switch": ["Troca Elétrica", "Volt Switch", "ELÉTRICO", "ESPECIAL", 70, 100],
  "water-gun": ["Revólver d'Água", "Water Gun", "ÁGUA", "ESPECIAL", 40, 100],
  "water-pulse": ["Pulso d'Água", "Water Pulse", "ÁGUA", "ESPECIAL", 60, 100],
  "wild-charge": ["Ataque Selvagem", "Wild Charge", "ELÉTRICO", "FÍSICO", 90, 100],
  "wood-hammer": ["Martelo de Madeira", "Wood Hammer", "PLANTA", "FÍSICO", 120, 100],
  "x-scissor": ["Tesoura X", "X-Scissor", "INSETO", "FÍSICO", 80, 100],
  "zap-cannon": ["Canhão Zap", "Zap Cannon", "ELÉTRICO", "ESPECIAL", 120, 50],
  "zen-headbutt": ["Cabeçada Zen", "Zen Headbutt", "PSÍQUICO", "FÍSICO", 80, 90],
});

// O poder-base preserva a referência dos jogos. O poder reduzido mantém a
// fórmula simples do IFighters jogável, sem apagar os metadados canônicos.
function equilibrarPoder(poderBase) {
  return Math.min(65, Math.round(30 + poderBase * 0.25));
}

function criarGolpe(id, definicao) {
  const [nome, nomeOriginal, tipo, categoria, poderBase, precisao, prioridade = 0] =
    definicao;

  return Object.freeze({
    id,
    nome,
    nomeOriginal,
    tipo,
    categoria,
    poder: equilibrarPoder(poderBase),
    poderBase,
    precisao,
    prioridade,
  });
}

const GOLPES = Object.freeze(
  Object.fromEntries(
    Object.entries(DEFINICOES_GOLPES).map(([id, definicao]) => [
      id,
      criarGolpe(id, definicao),
    ]),
  ),
);

function criarLutador({ atributos, golpes, tipos, ...dados }) {
  const movimentos = golpes.map((id) => {
    const movimento = GOLPES[id];

    if (!movimento) {
      throw new Error(`Golpe não cadastrado: ${id}`);
    }

    return movimento;
  });

  return Object.freeze({
    ...dados,
    tipos: Object.freeze([...tipos]),
    atributos: Object.freeze({ ...atributos }),
    golpes: Object.freeze(movimentos),
  });
}

const LUTADORES = Object.freeze([
  criarLutador({
    id: "arth",
    nome: "Arth",
    numero: 7,
    forma: "Squirtle",
    tipos: ["ÁGUA"],
    sprite: "img/sprites/arth-squirtle.png",
    descricao: "Combina sangue-frio, defesa e controle do ritmo da luta.",
    atributos: { vida: 112, ataque: 64, defesa: 78, velocidade: 56 },
    golpes: ["water-gun", "bite", "aqua-jet", "ice-beam"],
  }),
  criarLutador({
    id: "bertuol",
    nome: "Bertuol",
    numero: 644,
    forma: "Zekrom",
    tipos: ["DRAGÃO", "ELÉTRICO"],
    sprite: "img/sprites/bertuol-zekrom.png",
    descricao: "Avança com a força de uma tempestade e não cede terreno.",
    atributos: { vida: 145, ataque: 96, defesa: 84, velocidade: 90 },
    golpes: ["bolt-strike", "dragon-claw", "crunch", "zen-headbutt"],
  }),
  criarLutador({
    id: "bocussi",
    nome: "Bocussi",
    numero: 920,
    forma: "Lokix",
    tipos: ["INSETO", "SOMBRIO"],
    sprite: "img/sprites/bocussi-lokix.png",
    descricao: "Ataca antes que o adversário consiga organizar a resposta.",
    atributos: { vida: 116, ataque: 88, defesa: 66, velocidade: 94 },
    golpes: ["first-impression", "lunge", "throat-chop", "sucker-punch"],
  }),
  criarLutador({
    id: "cara-da-ti",
    nome: "Cara da TI",
    numero: 500,
    forma: "Emboar",
    tipos: ["FOGO", "LUTADOR"],
    sprite: "img/sprites/cara-da-ti-emboar.png",
    descricao: "Transforma potência bruta em pressão constante sobre o rival.",
    atributos: { vida: 138, ataque: 92, defesa: 72, velocidade: 62 },
    golpes: ["flare-blitz", "hammer-arm", "head-smash", "wild-charge"],
  }),
  criarLutador({
    id: "caua",
    nome: "Cauã",
    numero: 260,
    forma: "Swampert",
    tipos: ["ÁGUA", "TERRESTRE"],
    sprite: "img/sprites/caua-swampert.png",
    descricao: "Mantém os pés firmes e responde com força em qualquer terreno.",
    atributos: { vida: 140, ataque: 88, defesa: 86, velocidade: 58 },
    golpes: ["mud-shot", "liquidation", "earthquake", "ice-punch"],
  }),
  criarLutador({
    id: "cleci",
    nome: "Cleci",
    numero: 180,
    forma: "Flaaffy",
    tipos: ["ELÉTRICO"],
    sprite: "img/sprites/cleci-flaaffy.png",
    descricao: "Acumula energia com calma antes de descarregá-la no momento certo.",
    atributos: { vida: 118, ataque: 76, defesa: 66, velocidade: 62 },
    golpes: ["discharge", "power-gem", "thunder-punch", "thunderbolt"],
  }),
  criarLutador({
    id: "coelho",
    nome: "Coelho",
    numero: 815,
    forma: "Cinderace",
    tipos: ["FOGO"],
    sprite: "img/sprites/coelho-cinderace.png",
    descricao: "Domina a arena com técnica, mobilidade e finalizações precisas.",
    atributos: { vida: 124, ataque: 88, defesa: 70, velocidade: 102 },
    golpes: ["pyro-ball", "double-kick", "quick-attack", "u-turn"],
  }),
  criarLutador({
    id: "conceicao",
    nome: "Conceição",
    numero: 730,
    forma: "Primarina",
    tipos: ["ÁGUA", "FADA"],
    sprite: "img/sprites/conceicao-primarina.png",
    descricao: "Conduz a batalha com elegância sem abrir mão de poder ofensivo.",
    atributos: { vida: 128, ataque: 92, defesa: 78, velocidade: 66 },
    golpes: ["sparkling-aria", "moonblast", "aqua-jet", "psychic"],
  }),
  criarLutador({
    id: "dalcin",
    nome: "Dalcin",
    numero: 806,
    forma: "Blacephalon",
    tipos: ["FOGO", "FANTASMA"],
    sprite: "img/sprites/dalcin-blacephalon.png",
    descricao: "Usa criatividade explosiva para desmontar qualquer previsão.",
    atributos: { vida: 112, ataque: 98, defesa: 60, velocidade: 98 },
    golpes: ["mind-blown", "shadow-ball", "flamethrower", "astonish"],
  }),
  criarLutador({
    id: "davi",
    nome: "Davi",
    numero: 11,
    forma: "Metapod",
    tipos: ["INSETO"],
    sprite: "img/sprites/davi-metapod.png",
    descricao: "Resiste à pressão e prova que paciência também vence partidas.",
    atributos: { vida: 105, ataque: 46, defesa: 94, velocidade: 38 },
    // Tackle é retido do Caterpie; Struggle garante a quarta opção ofensiva.
    golpes: ["bug-bite", "electroweb", "tackle", "struggle"],
  }),
  criarLutador({
    id: "eraldo",
    nome: "Eraldo",
    numero: 377,
    forma: "Regirock",
    tipos: ["PEDRA"],
    sprite: "img/sprites/eraldo-regirock.png",
    descricao: "Sua resistência transforma cada troca de golpes em vantagem.",
    atributos: { vida: 142, ataque: 78, defesa: 104, velocidade: 40 },
    golpes: ["stone-edge", "hammer-arm", "zap-cannon", "stomp"],
  }),
  criarLutador({
    id: "filipe",
    nome: "Filipe",
    numero: 467,
    forma: "Magmortar",
    tipos: ["FOGO"],
    sprite: "img/sprites/filipe-magmortar.png",
    descricao: "Mantém o rival sob fogo cruzado com ampla cobertura ofensiva.",
    atributos: { vida: 126, ataque: 94, defesa: 72, velocidade: 78 },
    golpes: ["flamethrower", "thunderbolt", "psychic", "mach-punch"],
  }),
  criarLutador({
    id: "flores",
    nome: "Flores",
    numero: 376,
    forma: "Metagross",
    tipos: ["AÇO", "PSÍQUICO"],
    sprite: "img/sprites/flores-metagross.png",
    descricao: "Calcula cada risco antes de responder com precisão metálica.",
    atributos: { vida: 136, ataque: 90, defesa: 96, velocidade: 68 },
    golpes: ["meteor-mash", "zen-headbutt", "bullet-punch", "earthquake"],
  }),
  criarLutador({
    id: "jeferson",
    nome: "Jeferson",
    numero: 486,
    forma: "Regigigas",
    tipos: ["NORMAL"],
    sprite: "img/sprites/jeferson-regigigas.png",
    descricao: "Quando ganha impulso, sua força passa a ditar toda a batalha.",
    atributos: { vida: 150, ataque: 98, defesa: 90, velocidade: 78 },
    golpes: ["crush-grip", "giga-impact", "knock-off", "hammer-arm"],
  }),
  criarLutador({
    id: "kilder",
    nome: "Kilder",
    numero: 778,
    forma: "Mimikyu",
    variante: "Forma Disfarçada",
    tipos: ["FANTASMA", "FADA"],
    sprite: "img/sprites/kilder-mimikyu.png",
    descricao: "Esconde a intenção até o instante exato de virar o confronto.",
    atributos: { vida: 116, ataque: 86, defesa: 72, velocidade: 96 },
    golpes: ["play-rough", "shadow-claw", "shadow-sneak", "wood-hammer"],
  }),
  criarLutador({
    id: "kurt",
    nome: "Kurt",
    numero: 807,
    forma: "Zeraora",
    tipos: ["ELÉTRICO"],
    sprite: "img/sprites/kurt-zeraora.png",
    descricao: "A velocidade elétrica decide seus turnos antes da reação rival.",
    atributos: { vida: 120, ataque: 94, defesa: 68, velocidade: 108 },
    golpes: ["plasma-fists", "close-combat", "volt-switch", "quick-attack"],
  }),
  criarLutador({
    id: "laura",
    nome: "Laura",
    numero: 470,
    forma: "Leafeon",
    tipos: ["PLANTA"],
    sprite: "img/sprites/laura-leafeon.png",
    descricao: "Combina agilidade, disciplina e conexão com a natureza.",
    atributos: { vida: 120, ataque: 84, defesa: 88, velocidade: 90 },
    golpes: ["leaf-blade", "quick-attack", "dig", "x-scissor"],
  }),
  criarLutador({
    id: "lazzari",
    nome: "Lazzari",
    numero: 1,
    forma: "Bulbasaur",
    tipos: ["PLANTA", "VENENOSO"],
    sprite: "img/sprites/lazzari-bulbasaur.png",
    descricao: "Cresce durante o confronto e explora diferentes rotas de ataque.",
    atributos: { vida: 112, ataque: 70, defesa: 70, velocidade: 62 },
    golpes: ["vine-whip", "razor-leaf", "sludge-bomb", "seed-bomb"],
  }),
  criarLutador({
    id: "leonardo",
    nome: "Leonardo",
    numero: 448,
    forma: "Lucario",
    tipos: ["LUTADOR", "AÇO"],
    sprite: "img/sprites/leonardo-lucario.png",
    descricao: "Luta com precisão, leitura de aura e espírito de equipe.",
    atributos: { vida: 126, ataque: 88, defesa: 74, velocidade: 92 },
    golpes: ["aura-sphere", "metal-claw", "bone-rush", "quick-attack"],
  }),
  criarLutador({
    id: "lima",
    nome: "Lima",
    numero: 34,
    forma: "Nidoking",
    tipos: ["VENENOSO", "TERRESTRE"],
    sprite: "img/sprites/lima-nidoking.png",
    descricao: "Pressiona com variedade de tipos e golpes de grande alcance.",
    atributos: { vida: 130, ataque: 88, defesa: 74, velocidade: 86 },
    golpes: ["poison-jab", "earth-power", "megahorn", "ice-beam"],
  }),
  criarLutador({
    id: "lucas",
    nome: "Lucas",
    numero: 97,
    forma: "Hypno",
    tipos: ["PSÍQUICO"],
    sprite: "img/sprites/lucas-hypno.png",
    descricao: "Controla o ritmo com pressão mental e ataques imprevisíveis.",
    atributos: { vida: 128, ataque: 82, defesa: 76, velocidade: 70 },
    golpes: ["psychic", "psyshock", "zen-headbutt", "shadow-ball"],
  }),
  criarLutador({
    id: "luiz",
    nome: "Luiz",
    numero: 794,
    forma: "Buzzwole",
    tipos: ["INSETO", "LUTADOR"],
    sprite: "img/sprites/luiz-buzzwole.png",
    descricao: "Impõe presença física e converte resistência em poder ofensivo.",
    atributos: { vida: 142, ataque: 100, defesa: 86, velocidade: 76 },
    golpes: ["leech-life", "superpower", "lunge", "ice-punch"],
  }),
  criarLutador({
    id: "manfredini",
    nome: "Manfredini",
    numero: 28,
    forma: "Sandslash",
    tipos: ["TERRESTRE"],
    sprite: "img/sprites/manfredini-sandslash.png",
    descricao: "Abre caminho pela defesa adversária com garras e persistência.",
    atributos: { vida: 124, ataque: 84, defesa: 90, velocidade: 68 },
    golpes: ["drill-run", "earthquake", "slash", "x-scissor"],
  }),
  criarLutador({
    id: "marcelo",
    nome: "Marcelo",
    numero: 194,
    forma: "Wooper",
    tipos: ["ÁGUA", "TERRESTRE"],
    sprite: "img/sprites/marcelo-wooper.png",
    descricao: "Vence pela simplicidade, resistência e escolhas bem colocadas.",
    atributos: { vida: 110, ataque: 62, defesa: 60, velocidade: 40 },
    golpes: ["water-gun", "mud-shot", "slam", "mud-bomb"],
  }),
  criarLutador({
    id: "marcos",
    nome: "Marcos",
    numero: 657,
    forma: "Frogadier",
    tipos: ["ÁGUA"],
    sprite: "img/sprites/marcos-frogadier.png",
    descricao: "Muda de posição sem aviso e pune qualquer espaço disponível.",
    atributos: { vida: 114, ataque: 78, defesa: 64, velocidade: 96 },
    golpes: ["water-pulse", "quick-attack", "bounce", "ice-beam"],
  }),
  criarLutador({
    id: "mateus",
    nome: "Mateus",
    numero: 650,
    forma: "Chespin",
    tipos: ["PLANTA"],
    sprite: "img/sprites/mateus-chespin.png",
    descricao: "Compensa o tamanho com coragem e ataques difíceis de prever.",
    atributos: { vida: 110, ataque: 68, defesa: 74, velocidade: 56 },
    golpes: ["vine-whip", "bite", "pin-missile", "seed-bomb"],
  }),
  criarLutador({
    id: "mineia",
    nome: "Mineia",
    numero: 648,
    forma: "Meloetta",
    variante: "Forma Ária",
    tipos: ["NORMAL", "PSÍQUICO"],
    sprite: "img/sprites/mineia-meloetta.png",
    descricao: "Transforma ritmo e expressão em uma ofensiva versátil.",
    atributos: { vida: 132, ataque: 90, defesa: 80, velocidade: 96 },
    golpes: ["relic-song", "psychic", "hyper-voice", "quick-attack"],
  }),
  criarLutador({
    id: "mohamed",
    nome: "Mohamed",
    numero: 214,
    forma: "Heracross",
    tipos: ["INSETO", "LUTADOR"],
    sprite: "img/sprites/mohamed-heracross.png",
    descricao: "Entra em combate direto e sustenta a pressão até o fim.",
    atributos: { vida: 130, ataque: 94, defesa: 76, velocidade: 84 },
    golpes: ["megahorn", "close-combat", "bullet-seed", "aerial-ace"],
  }),
  criarLutador({
    id: "mussato",
    nome: "Mussato",
    numero: 274,
    forma: "Nuzleaf",
    tipos: ["PLANTA", "SOMBRIO"],
    sprite: "img/sprites/mussato-nuzleaf.png",
    descricao: "Alterna astúcia e golpes cortantes para quebrar o plano rival.",
    atributos: { vida: 116, ataque: 76, defesa: 62, velocidade: 76 },
    golpes: ["leaf-blade", "foul-play", "extrasensory", "razor-leaf"],
  }),
  criarLutador({
    id: "patrick",
    nome: "Patrick",
    numero: 493,
    forma: "Arceus",
    tipos: ["NORMAL"],
    sprite: "img/sprites/patrick-arceus.png",
    descricao: "Adapta-se ao confronto e responde com domínio absoluto da arena.",
    atributos: { vida: 150, ataque: 100, defesa: 96, velocidade: 100 },
    golpes: ["judgment", "extreme-speed", "earth-power", "shadow-claw"],
  }),
  criarLutador({
    id: "pedro",
    nome: "Pedro",
    numero: 151,
    forma: "Mew",
    tipos: ["PSÍQUICO"],
    sprite: "img/sprites/pedro-mew.png",
    descricao: "Sua flexibilidade oferece uma resposta diferente para cada ameaça.",
    atributos: { vida: 138, ataque: 92, defesa: 88, velocidade: 92 },
    golpes: ["psychic", "aura-sphere", "ice-beam", "ancient-power"],
  }),
  criarLutador({
    id: "presidente",
    nome: "Presidente",
    numero: 471,
    forma: "Glaceon",
    tipos: ["GELO"],
    sprite: "img/sprites/presidente-glaceon.png",
    descricao: "Esfria o ímpeto adversário e escolhe com cuidado quando avançar.",
    atributos: { vida: 120, ataque: 90, defesa: 84, velocidade: 72 },
    golpes: ["ice-beam", "freeze-dry", "quick-attack", "shadow-ball"],
  }),
  criarLutador({
    id: "roque",
    nome: "Roque",
    numero: 4,
    forma: "Charmander",
    tipos: ["FOGO"],
    sprite: "img/sprites/roque-charmander.png",
    descricao: "Mantém a chama acesa e acelera conforme a disputa esquenta.",
    atributos: { vida: 108, ataque: 70, defesa: 58, velocidade: 76 },
    golpes: ["ember", "dragon-breath", "scratch", "flame-charge"],
  }),
  criarLutador({
    id: "sandro",
    nome: "Sandro",
    numero: 94,
    forma: "Gengar",
    tipos: ["FANTASMA", "VENENOSO"],
    sprite: "img/sprites/sandro-gengar.png",
    descricao: "Ataca pelos ângulos mortos e nunca revela todo o seu plano.",
    atributos: { vida: 118, ataque: 94, defesa: 68, velocidade: 104 },
    golpes: ["shadow-ball", "sludge-bomb", "lick", "dark-pulse"],
  }),
  criarLutador({
    id: "somacal",
    nome: "Somacal",
    numero: 724,
    forma: "Decidueye",
    tipos: ["PLANTA", "FANTASMA"],
    sprite: "img/sprites/somacal-decidueye.png",
    descricao: "Mira com calma e encerra a distância com ataques certeiros.",
    atributos: { vida: 126, ataque: 88, defesa: 74, velocidade: 78 },
    golpes: ["spirit-shackle", "leaf-blade", "brave-bird", "shadow-sneak"],
  }),
  criarLutador({
    id: "tibolla",
    nome: "Tibolla",
    numero: 479,
    forma: "Rotom",
    tipos: ["ELÉTRICO", "FANTASMA"],
    sprite: "img/sprites/tibolla-rotom.png",
    descricao: "Circula pelo campo e desestabiliza o adversário com energia pura.",
    atributos: { vida: 116, ataque: 86, defesa: 74, velocidade: 98 },
    golpes: ["thunderbolt", "shadow-ball", "discharge", "astonish"],
  }),
  criarLutador({
    id: "witt",
    nome: "Witt",
    numero: 103,
    forma: "Exeggutor",
    variante: "Forma de Alola",
    tipos: ["PLANTA", "DRAGÃO"],
    sprite: "img/sprites/witt-exeggutor.png",
    descricao: "Enxerga a disputa de cima e responde com força dracônica.",
    atributos: { vida: 134, ataque: 90, defesa: 78, velocidade: 48 },
    golpes: ["dragon-hammer", "dragon-pulse", "psychic", "solar-beam"],
  }),
]);

if (typeof module !== "undefined" && module.exports) {
  module.exports = LUTADORES;
}
