name: Testes

on:
  push:
    branches:
      - main
      - "fix/**"
  pull_request:

jobs:
  testes:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Executar testes
        run: npm test
